### ISSUE TITLE
Menu k Offer vypadá otřesně

### ISSUE THREAD

**Issue by cshaa** [hokynar-org/knihovnik#1]
![image](https://github.com/hokynar-org/knihovnik/assets/1671665/b48b47ab-7363-4033-a757-76256dd7416e)

Somebody fix pls.

**Comment by cshaa** [comment]
(Tohle byl vzorový issue, na kterém jsem Kristýně ukazoval, jak se zakládají issues)

**Comment by JindrazPrahy** [comment]
Fixed
