### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by RisaI** [hokynar-org/knihovnik#3]
Nemáme žádnou layout strategy pro mobil/ostatní breakpointy.

![image](https://github.com/hokynar-org/knihovnik/assets/7413196/ebba3dc0-6539-4704-99cd-7db2f0a3e17d)

Navrhuji dělat aplikaci mobile-first a větší obrazovky řešit pomocí [Tailwindu](https://tailwindcss.com/docs/responsive-design).

**Comment by JindrazPrahy** [comment]
Už používáme Tailwind a Skeleton. Nějaká responzivita tam je. Pro další enhancementy, nechť jsou detailnější issues.
